default_agent: agentcore_lang_runtime
agents:
  agentcore_lang_runtime:
    name: agentcore_lang_runtime
    language: python
    node_version: '20'
    entrypoint: C:/Users/santh/Downloads/agentcore-demo/01_agentcore_runtime.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\santh\Downloads\agentcore-demo
    aws:
      execution_role: arn:aws:iam::704798089040:role/AmazonBedrockAgentCoreSDKRuntime-ap-south-2-c980c3716d
      execution_role_auto_create: false
      account: '704798089040'
      region: ap-south-2
      ecr_repository: 704798089040.dkr.ecr.ap-south-2.amazonaws.com/bedrock-agentcore-agentcore_lang_runtime
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-agentcore_lang_runtime-builder
      execution_role: arn:aws:iam::704798089040:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-south-2-c980c3716d
      source_bucket: bedrock-agentcore-codebuild-sources-704798089040-ap-south-2
    memory:
      mode: STM_AND_LTM
      memory_id: null
      memory_arn: null
      memory_name: agentcore_lang_runtime_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
